### ISSUE TITLE
[ToDo] basic player interface

### ISSUE THREAD

**Issue by mosemister** [TerraTerma/Core#17]
ever heard of minecraft bukkit GUIS? they are just a chest inventory but when you click on a item, it does something.

there needs to be a easy to use object setup class for one of these.

I want it so there is a minimum of blank slots. You have permission to use my Ships plugin code for this one (why reinvent the wheel)

**Comment by cgameing** [comment]
Can you teach me how to do that mosemister

**Comment by mosemister** [comment]
sure thing, ill send you the commit when its done

**Comment by mosemister** [comment]
@cgameing 
#17
