### ISSUE TITLE
[ToDo] Cool way of dying for respawn minigames

### ISSUE THREAD

**Issue by cgameing** [TerraTerma/Core#30]
----Low priority/------
I found a cool way of dying on another server
Basicly just check for death and when they die, make them invisible infinitly slow so the can see who killed then.

Then have a title message (thats the vanilla command im not sure what to call it) that counts down from 3 (or a custom int/long) and then says left click to respawn

Soz for the huge amount for text and as stated before its low priority. Thanks

**Comment by mosemister** [comment]
On PlayerDamageEvent if the defender will die from the attack, then set defender invisible, cancel event and set player speed (using the old way). after that set 3 delay timed run sequences, (A +1 = (A*20)) each one giving a message of A.

that way is probably the most efficient way of doing such a thing.

As for the message, we will determine if it is low or high priority and its really not that much XD

**Comment by cgameing** [comment]
Got another idea that shouldent be hard to impliment
Add a boolean on whether its a respawn minigame or not, and if it isnt then put the player in spectator

**Comment by cgameing** [comment]
But keep the 3 second wait, its so you see who killed you

**Comment by mosemister** [comment]
Yeah the (A*20) is 3 seconds (20 ticks in a second)
